version: "3.8"
services:
  db:
    container_name: rust-fullstack-db
    image: postgres:15.3
    ports:
      - "5432:5432"
    command: postgres -c max_connections=500
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file: 
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - rust-fullstack-network

  backend:
    container_name: rust-fullstack-backend
    restart: always
    build: 
      context: ./rust-backend-template
    volumes:
      - ./rust-backend-template:/code/app
    ports:
      - 3000:3000
    env_file: 
      - ./.env
    networks:
      - rust-fullstack-network
    command: cargo run

  frontend:
    container_name: rust-fullstack-frontend
    restart: always
    build: 
        context: ./rust-frontend-template
    volumes:
      - ./rust-frontend-template:/app
      - /app/node_modules/
    ports:
      - 5173:5173
    networks:
      - rust-fullstack-network
    command: npm run dev -- --host

networks:
  rust-fullstack-network:
    driver: bridge
    external: true
    name: rust-fullstack-network